#!/usr/bin/env bash
#

cat ~/Downloads/activity_20190816-102940.csv|awk -F"," '{print $2 "\t" $3}' >> log

# fix date format!
#   ctrl-v G d to delete extra space
#   ctrl-v G :s/\t/:00\t/g to add seconds to time
# comment out any comments that should not be parsed
# change Eletriptan to 40mg eletriptan
# change Domperidon to 10mg domperidon
# make sure last line is not blank
# run the following

mkdir -p data/parsed
mkdir plots

python parse_clue.py $(find . -type f -name "ClueBackup-*" |sort|tail -n 1) |sort|uniq|grep -E 'light|medium|heavy|spotting' > data/parsed/clue.read
cat data/log | grep -v "#" | grep -i aura > data/parsed/aura
cat data/log | grep -v "#" | grep -i naus > data/parsed/nausea
grep -v "#" data/log|grep triptan|sed 's/mg /	/' > data/parsed/drugs
grep preventative data/log|sed 's/preventative.*$//'|sed 's/mg /	/' > data/preventatives
python parse_preventatives data/preventatives > data/parsed/preventatives_start_end

cat data/log | grep -v "#" | grep -vi aura | grep -vi naus | grep -v mg | grep -v cannabis |grep -v amitriptiline |grep -v preventative|sort > data/migraine_current
cat data/migraine_historical data/migraine_current > data/migraine
python parse_migraine.py data/migraine > data/parsed/migraine_start_end

./COMMANDS.R

#---- unused
#python parse_myfitnesspal.py > clean_data/food-sept   # per month, then clean food names
#cat clean_data/daily-drugs <(cat clean_data/log | grep -v "#" | egrep -i "mg|cannabis|amitriptyline") | sed s/mg// | sort > clean_data/drugs
#open in vi and :%s/mg /^I/g and :%s/cannabis/^Icannabis/g
